sudo: required
dist: xenial
language: go

services:
  - docker
  
script:
  - chmod +x hello.py
  - ./hello.py 
  - docker build --tag hello:v1 .
  - docker images
  - docker run hello:v1
 
after_script:
  - echo "Image built and run sucessfully"
